### ISSUE TITLE
The tool tip closes when changing the skill level.

### ISSUE THREAD

**Issue by hidekuro** [spacem/dnskillsim#5]
The tool tip closes when changing the skill level.
Previously the tooltips did not disappear even if the level was changed.
Can I leave the tool tip open even if I change the skill level?

**Comment by hidekuro** [comment]
no one here 🤷

**Comment by spacem** [comment]
Thanks for the suggestion I will try to keep it running and fix any problems that come up but I don't have any motivation to extend the skill sim further at this time.
